name: Slash command validation

on: [push, pull_request, workflow_dispatch]

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate JSON files
      run: bash ./scripts/validate-slash_commands.sh ./slash-commands
